baseurl = "https://tiangolo.netlify.com/"
languageCode = "en-US"
title = "tiangolo - Sebastián Ramírez"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "tiangolo - Sebastián Ramírez"
  description = "I do AI and stuff... and lots of Open Source. Deep Learning, Data Science and full stack distributed systems."

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/custom.css"]
  custom_js  = []

[params.social]
  Github        = "tiangolo"
  Email         = "tiangolo@gmail.com"
  Twitter       = "tiangolo"
  LinkedIn      = "tiangolo"
  # Stackoverflow = "username"
  Medium        = "tiangolo"
  # Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://medium.com/@tiangolo"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
